export enum Actions {
  NEW_TODO = 'NEW_TODO',
  CHANGE_TODO_STATE = 'CHANGE_TODO_STATE',
  IS_ADDING = 'IS_ADDING',
  EDIT_TODO = 'EDIT_TODO',
  IS_EDITING = 'IS_EDITING',
  SET_SHOWING = 'SET_SHOWING',
  SET_SORTING = 'SET_SORTING',
}